# 服务器端口
server:
  port: 8088

# Spring 核心配置
spring:
  # 应用名称
  application:
    name: xyx-trade

  # MVC 路径匹配（Swagger/Knife4j 必须）
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # 文件上传配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB

  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xyx_campus_db?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

  # Redis 配置
  redis:
    host: localhost
    port: 6379
    password:  # 没有就空
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

  # 允许覆盖Bean
  main:
    allow-bean-definition-overriding: true

# MyBatis-Plus 配置
mybatis-plus:
  # 别名包扫描
  type-aliases-package: com.xyx.trade.**.domain
  # Mapper XML 文件位置
  mapper-locations: classpath:mapper/*.xml
  # 配置
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: is_deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# 日志配置
logging:
  level:
    # 关闭 Swagger 无用警告
    springfox.documentation.spring.web.readers.operation: ERROR
    springfox.documentation: ERROR
    # 关闭 MyBatis-Plus 重复注入警告
    com.baomidou.mybatisplus: WARN
    # 关闭 ReflectLambdaMeta Java17 反射警告
    com.baomidou.mybatisplus.core.toolkit.support: ERROR
    # 关闭 Tomcat 多余日志
    org.apache.tomcat: WARN
    org.apache.catalina: WARN
    org.apache.coyote: WARN
    # 保留业务日志
    com.xyx.trade: INFO